### ISSUE TITLE
Dependency tooltip

### ISSUE THREAD

**Issue by Jiyambi** [Jiyambi/WoW-Pro-Guides#128]
Need a tooltip displaying what quest the step is dependent on.

Will make a table of dependency names during the guide load, using the |PRE| tags. Will check each step with a pre tag, then get the name of an accept or turn in steps with that QID. That will become the value for the dependency table. Then will fill in that value for all steps with a QID equal to the original step with the |PRE| tag in it.

Once the dependency table is populated, shouldn't be too hard to put in tooltips for hover over in the current guide panel. However I'm tooltip challenged, so some assistance with utilizing the game's tooltip system would be much appreciated.

**Comment by Ludovicus** [comment]
The current guide listing now displays tons of information about that step, including what conditions led to it not being available:  dependencies, professions, levels, race, class, ... .

Close enuf!
