### ISSUE TITLE
New Ability or Talent Point Reminder

### ISSUE THREAD

**Issue by Jiyambi** [Jiyambi/WoW-Pro-Guides#241]
A simple icon which appears somewhere stuck to the guide frame - lets the user know they have an ability to learn or a talent point to spend. Stays until the user learns the ability/spends the talent point, or until manually dismissed. Obviously can be turned off if desired.

Should be able to display a summary of what is learn-able on hover-over.

Figure this could just be part of the leveling module rather than a separate module. Probably warrants it's own little lua file.

**Comment by Ludovicus** [comment]
This feature broke for the Pandaria expansion and was excised.
The game defaults are now not so bad.
