### ISSUE TITLE
Attempt to index field '?' (a nil value)

### ISSUE THREAD

**Issue by Aldavor** [Jiyambi/WoW-Pro-Guides#394]
Obtaining this error on some accounts on startup, and others at random places, usually after taking a flight point that crosses zones.

Date: 2015-01-11 10:54:45
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\WoWPro\WoWPro_Parser.lua line 419:
   attempt to index field '?' (a nil value)
Debug:
   WoWPro\WoWPro_Parser.lua:419:
      WoWPro\WoWPro_Parser.lua:398
   (tail call): ?
   [C]: ?
   [string "safecall Dispatcher[1]"]:9:
      [string "safecall Dispatcher[1]"]:5
   (tail call): ?
   ...nterface\AddOns\Ace3\AceBucket-3.0\AceBucket-3.0.lua:118: func()
   Ace3\AceTimer-3.0\AceTimer-3.0.lua:55:
      Ace3\AceTimer-3.0\AceTimer-3.0.lua:48
Locals:
None
AddOns:
  BlizzBugsSuck, v6.0.3.2
  Swatter, v5.21c.5521 (SanctimoniousSwamprat)
  Accountant, v6.01.60000
  Ace3, v
  ACP, v3.4.14 
  Arh, v1.4.2
  AskMrRobot, v19
  AucAdvanced, v5.21c.5521 (SanctimoniousSwamprat)
  AucFilterBasic, v5.21c.5521 (SanctimoniousSwamprat)
  AucFilterOutlier, v5.21c.5521.5459(5.21c/embedded)
  AucMatchUndercut, v5.21c.5521.5507(5.21c/embedded)
  AucStatHistogram, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatiLevel, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatPurchased, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatSales, v5.21c.5521.5476(5.21c/embedded)
  AucStatSimple, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatStdDev, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatWOWEcon, v5.21c.5521.5323(5.21c/embedded)
  AucUtilAHWindowControl, v5.21c.5521.5347(5.21c/embedded)
  AucUtilAppraiser, v5.21c.5521.5495(5.21c/embedded)
  AucUtilAskPrice, v5.21c.5521.5447(5.21c/embedded)
  AucUtilAutoMagic, v5.21c.5521.5443(5.21c/embedded)
  AucUtilCompactUI, v5.21c.5521.5496(5.21c/embedded)
  AucUtilEasyBuyout, v5.21c.5521.5507(5.21c/embedded)
  AucUtilFixAH, v5.21c.5521 (SanctimoniousSwamprat)
  AucUtilItemSuggest, v5.21c.5521.5417(5.21c/embedded)
  AucUtilPriceLevel, v5.21c.5521.5458(5.21c/embedded)
  AucUtilScanButton, v5.21c.5521.5403(5.21c/embedded)
  AucUtilScanFinish, v5.21c.5521.5515(5.21c/embedded)
  AucUtilScanProgress, v5.21c.5521.4979(5.21c/embedded)
  AucUtilScanStart, v5.21c.5521.5347(5.21c/embedded)
  AucUtilSearchUI, v5.21c.5521.5515(5.21c/embedded)
  AucUtilSimpleAuction, v5.21c.5521.5514(5.21c/embedded)
  AucUtilVendMarkup, v5.21c.5521.4828(5.21c/embedded)
  Babylonian, v5.1.DEV.332(/embedded)
  BadBoy, v12.504
  BagBrother, v6.0.16
  Bagnon, v6.0.16
  BagnonConfig, v6.0.16
  Bazooka, vv2.4.2
  BeanCounter, v5.21c.5521 (SanctimoniousSwamprat)
  Breeze, vv1.10
  ButtonForge, v0.9.38
  Carbonite, v6.0.1
  CarboniteInfo, v1.0
  CarboniteNotes, v1.1
  CarboniteNotesSample, v1.0
  CarboniteQuests, v1.0
  CarboniteSocial, v1.0
  CarboniteWarehouse, v1.0
  CarboniteWeekly, v1.0
  Configator, v5.1.DEV.376(/embedded)
  DebugLib, v5.1.DEV.337(/embedded)
  GatherMate2, v1.33.3
  Grail, v067
  HealBot, v6.0.3.8
  HealBotTips, v6.0.3.8
  Informant, v5.21c.5521 (SanctimoniousSwamprat)
  LibExtraTip, v5.12.DEV.363(/embedded)
  MasterPlan, v0.23
  MineOMatic, v6.0.3.007
  MogIt, v3.4.0
  MyBits, v
  NugComboBar, v
  NugComboBarGUI, v
  omouse, v0.1.4
  Pawn, v1.9.12
  Postal, v3.5.1
  Skada, v1.4-27
  Stubby, v5.21c.5521 (SanctimoniousSwamprat)
  TheUndermineJournal, v3.2.20150110
  TipHelper, v5.12.DEV.351(/embedded)
  TomTom, vv60000-1.1.1
  WIM, v3.6.23
  WoWPro, v6.0.3J
  WoWProAchievements, v6.0.3J
  WoWProDailies, v6.0.3J
  WoWProLeveling, v6.0.3J
  WowProProfession, v6.0.3J
  WoWProWorldEvents, v6.0.3J
  BlizRuntimeLib_enUS v6.0.3.60000 <none>
  (ck=af6)

**Comment by Ludovicus** [comment]
Hmm, What Module/Guide were you using?

**Comment by Aldavor** [comment]
Sorry, didn't have debug mode on... forgot. Now enabled.
The particular error above was effected on login after character selection, and I was in the lunarfall garrison. The stored guide I believe was Shadowmoon Valley, Draenor. However, in some cases, the same error but with a different line number (276 I believe) occurs with different zones enabled, but always just as I log in with a character. Note this only happens with some, not all.

I'll post the next error I get with debug information as I get it.

**Comment by Ludovicus** [comment]
No need to have debug mode on.   The log always contains useful information.   Debug mode just opens up the faucet wide open.

Since I see you have swatter, you can scroll back in the error history and post some of the other errors happening on other lines.   They could be different errors!

**Comment by Aldavor** [comment]
Just got this one immediately after logging on my lvl 93 Paladin character; I was in the Garrison, standing at the mission table.

Date: 2015-01-13 07:29:56
ID: 1
Error occured in: Global
Count: 1
Message: ...dOns\WoWPro\Libraries\Astrolabe\Astrolabe-TomTom.lua line 276:
   attempt to index field '?' (a nil value)
Debug:
   ...dOns\WoWPro\Libraries\Astrolabe\Astrolabe-TomTom.lua:276: TranslateWorldMapPosition()
   ...dOns\WoWPro\Libraries\Astrolabe\Astrolabe-TomTom.lua:1056: PlaceIconOnWorldMap()
   TomTom\TomTom_Waypoints.lua:411:
      TomTom\TomTom_Waypoints.lua:403
   [C]: ?
   Carbonite\NxMap.lua:248: SetMapByID()
   Carbonite.Quests\NxQuest.lua:3713: func()
   Ace3\AceTimer-3.0\AceTimer-3.0.lua:55:
      Ace3\AceTimer-3.0\AceTimer-3.0.lua:48
Locals:
self = <table> {
 IconsOnEdge_GroupChangeCallbacks = <table> {
 }
 GetIconAssociation = <function> defined @Interface\AddOns\WoWPro\Libraries\Astrolabe\Astrolabe-TomTom.lua:944
 CalculateMinimapIconPositions = <function> defined @Interface\AddOns\WoWPro\Libraries\Astrolabe\Astrolabe-TomTom.lua:887
 AllWorldMapsHidden = <function> defined @Interface\AddOns\WoWPro\Libraries\Astrolabe\Astrolabe-TomTom.lua:1164
 RemoveIconFromMinimap = <function> defined @Interface\AddOns\WoWPro\Libraries\Astrolabe\Astrolabe-TomTom.lua:624
 TargetMinimapChanged_Callbacks = <table> {
 }
 PlaceIconOnMinimap = <function> defined @Interface\AddOns\WoWPro\Libraries\Astrolabe\Astrolabe-TomTom.lua:539
 SetEdgeRangeMultiplier = <function> defined @Interface\AddOns\WoWPro\Libraries\Astrolabe\Astrolabe-TomTom.lua:948
 ComputeDistance = <function> defined @Interface\AddOns\WoWPro\Libraries\Astrolabe\Astrolabe-TomTom.lua:177
 IconsOnEdge = <table> {
 }
 OnShow = <function> defined @Interface\AddOns\WoWPro\Libraries\Astrolabe\Astrolabe-TomTom.lua:1132
 GetUnitPosition = <function> defined @Interface\AddOns\WoWPro\Libraries\Astrolabe\Astrolabe-TomTom.lua:324
 GetDirectionToIcon = <function> defined @Interface\AddOns\WoWPro\Libraries\Astrolabe\Astrolabe-TomTom.lua:924
 IconsOnEdgeChanged = false
 PlaceIconOnWorldMap = <function> defined @Interface\AddOns\WoWPro\Libraries\Astrolabe\Astrolabe-TomTom.lua:1044
 GetNumFloors = <function> defined @Interface\AddOns\WoWPro\Libraries\Astrolabe\Astrolabe-TomTom.lua:409
 GetMapInfo = <function> defined @Interface\AddOns\WoWPro\Libraries\Astrolabe\Astrolabe-TomTom.lua:416
 MicroDungeonSize = <table> {
 }
 GetMapFilename = <function> defined @Interface\AddOns\WoWPro\Libraries\Astrolabe\Astrolabe-TomTom.lua:432
 UpdateMinimapIconPositions = <function> defined @Interface\AddOns\WoWPro\Libraries\Astrolabe\Astrolabe-TomTom.lua:789
 GetCurrentPlayerPosition = <function> defined @Interface\AddOns\WoWPro\Libraries\Astrolabe\Astrolabe-TomTom.lua:369
 DumpNewIconsCache = <function> defined @Interface\AddOns\WoWPro\Libraries\Astrolabe\Astrolabe-TomTom.lua:1028
 zeroData = <table> {
 }
 WorldMapSize = <table> {
 }
 MinimapIconCount = 1
 EdgeRangeMultiplier = <table> {
 }
 SetTargetMinimap = <function> defined @Interface\AddOns\WoWPro\Libraries\Astrolabe\Astrolabe-TomTom.lua:987
 HarvestedMapData = <table> {
 }
 processingFrame = <unnamed> {
 }
 GetVersion = <function> defined @Interface\AddOns\WoWPro\Libraries\Astrolabe\Astrolabe-TomTom.lua:55
 Minimap = Minimap {
 }
 GetEdgeRangeMultiplier = <function> defined @Interface\AddOns\WoWPro\Libraries\Astrolabe\Astrolabe-TomTom.lua:977
 WorldMapVisible = false
 OnUpdate = <function> defined @Interface\AddOns\WoWPro\Libraries\Astrolabe\Astrolabe-TomTom.lua:1120
 AssociateIcon = <function> defined @Interface\AddOns\WoWPro\Libraries\Astrolabe\Astrolabe-TomTom.lua:936
 minimapOutside = false
 Register_TargetMinimapChanged_Callback = <function> defined @Interface\AddOns\WoWPro\Libraries\Astrolabe\Astrolabe-TomTom.lua:1017
 ContinentList = <table> {
 }
 Register_OnEdgeChanged_Callback = <function> defined @Interface\AddOns\WoWPro\Libraries\Astrolabe\Astrolabe-TomTom.lua:982
 MinimapUpdateMultiplier = 1
 OnHide = <function> defined @Interface\AddOns\WoWPro\Libraries\Astrolabe\Astrolabe-TomTom.lua:1157
 MinimapIcons = <table> {
 }
 TranslateWorldMapPosition = <function> defined @Interface\AddOns\WoWPro\Libraries\Astrolabe\Astrolabe-TomTom.lua:247
 OnEvent = <function> defined @Interface\AddOns\WoWPro\Libraries\Astrolabe\Astrolabe-TomTom.lua:1074
 GetMapID = <function> defined @Interface\AddOns\WoWPro\Libraries\Astrolabe\Astrolabe-TomTom.lua:398
 DefaultEdgeRangeMultiplier = 1
 IsIconOnEdge = <function> defined @Interface\AddOns\WoWPro\Libraries\Astrolabe\Astrolabe-TomTom.lua:920
 GetDistanceToIcon = <function> defined @Interface\AddOns\WoWPro\Libraries\Astrolabe\Astrolabe-TomTom.lua:913
 ForceNextUpdate = false
 LastPlayerPosition = <table> {
 }
 IconAssociations = <table> {
 }
 RemoveAllMinimapIcons = <function> defined @Interface\AddOns\WoWPro\Libraries\Astrolabe\Astrolabe-TomTom.lua:644
}

AddOns:
  BlizzBugsSuck, v6.0.3.2
  Swatter, v5.21c.5521 (SanctimoniousSwamprat)
  Accountant, v6.01.60000
  Ace3, v
  ACP, v3.4.14 
  Arh, v1.4.2
  AskMrRobot, v19
  AucAdvanced, v5.21c.5521 (SanctimoniousSwamprat)
  AucFilterBasic, v5.21c.5521 (SanctimoniousSwamprat)
  AucFilterOutlier, v5.21c.5521.5459(5.21c/embedded)
  AucMatchUndercut, v5.21c.5521.5507(5.21c/embedded)
  AucStatHistogram, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatiLevel, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatPurchased, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatSales, v5.21c.5521.5476(5.21c/embedded)
  AucStatSimple, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatStdDev, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatWOWEcon, v5.21c.5521.5323(5.21c/embedded)
  AucUtilAHWindowControl, v5.21c.5521.5347(5.21c/embedded)
  AucUtilAppraiser, v5.21c.5521.5495(5.21c/embedded)
  AucUtilAskPrice, v5.21c.5521.5447(5.21c/embedded)
  AucUtilAutoMagic, v5.21c.5521.5443(5.21c/embedded)
  AucUtilCompactUI, v5.21c.5521.5496(5.21c/embedded)
  AucUtilEasyBuyout, v5.21c.5521.5507(5.21c/embedded)
  AucUtilFixAH, v5.21c.5521 (SanctimoniousSwamprat)
  AucUtilItemSuggest, v5.21c.5521.5417(5.21c/embedded)
  AucUtilPriceLevel, v5.21c.5521.5458(5.21c/embedded)
  AucUtilScanButton, v5.21c.5521.5403(5.21c/embedded)
  AucUtilScanFinish, v5.21c.5521.5515(5.21c/embedded)
  AucUtilScanProgress, v5.21c.5521.4979(5.21c/embedded)
  AucUtilScanStart, v5.21c.5521.5347(5.21c/embedded)
  AucUtilSearchUI, v5.21c.5521.5515(5.21c/embedded)
  AucUtilSimpleAuction, v5.21c.5521.5514(5.21c/embedded)
  AucUtilVendMarkup, v5.21c.5521.4828(5.21c/embedded)
  Babylonian, v5.1.DEV.332(/embedded)
  BadBoy, v12.504
  BagBrother, v6.0.16
  Bagnon, v6.0.16
  Bazooka, vv2.4.2
  BeanCounter, v5.21c.5521 (SanctimoniousSwamprat)
  ButtonForge, v0.9.38
  Carbonite, v6.0.1
  CarboniteInfo, v1.0
  CarboniteNotes, v1.1
  CarboniteNotesSample, v1.0
  CarboniteQuests, v1.0
  CarboniteSocial, v1.0
  CarboniteWarehouse, v1.0
  CarboniteWeekly, v1.0
  Configator, v5.1.DEV.376(/embedded)
  DebugLib, v5.1.DEV.337(/embedded)
  Enchantrix, v5.21c.5521 (SanctimoniousSwamprat)
  EnchantrixBarker, v5.21c.5521 (SanctimoniousSwamprat)
  GatherMate2, v1.33.4
  Grail, v067
  HealBot, v6.0.3.9
  HealBotTips, v6.0.3.9
  Informant, v5.21c.5521 (SanctimoniousSwamprat)
  LibExtraTip, v5.12.DEV.363(/embedded)
  MineOMatic, v6.0.3.007
  MogIt, v3.4.0
  MyBits, v
  NugComboBar, v
  omouse, v0.1.4
  Pawn, v1.9.12
  Postal, v3.5.1
  Skada, v1.4-27
  Stubby, v5.21c.5521 (SanctimoniousSwamprat)
  TheUndermineJournal, v3.2.20150110
  TipHelper, v5.12.DEV.351(/embedded)
  TomTom, vv60000-1.1.1
  WIM, v3.6.23
  WoWPro, v6.0.3J
  WoWProAchievements, v6.0.3J
  WoWProDailies, v6.0.3J
  WoWProLeveling, v6.0.3J
  WowProProfession, v6.0.3J
  WoWProWorldEvents, v6.0.3J
  BlizRuntimeLib_enUS v6.0.3.60000 <none>
  (ck=b0f)

**Comment by Ludovicus** [comment]
Ohh, this is interesting.   Carbonite, calling TomTom, then calling out enhanced Astrolabe libraries.

Map data is sent to the client by the server relatively late as compared to the Pandaria client.

**Comment by Aldavor** [comment]
Great :) please let me know if I can do anything.

**Comment by nelegalno** [comment]
Currently Carbonite and TomTom are incompatible - should not be used together until the authors implement some way for them to play nice when used together. And if you intend to use Carbonite for waypoints the authors of WoWPro would probably have to update the code so it can work with the updated version of Carbonite http://www.wowinterface.com/downloads/index.php?cid=138&sortby=dec_hits and https://github.com/Rythal/Carbonite for the dev version.

**Comment by Ludovicus** [comment]
Thanks nelgaino for the information.

We have code in WoW-Pro to play nice with Carbonite's TomTom compatability interface.

Aldavor:  If you can get the debug log to correspond with the original problem you reported, I will fix it!

**Comment by Aldavor** [comment]
Many thanks for this. I actually download the most current git repository Carbonite files (https://github.com/Rythal/Carbonite) and usually check daily for updates.

Ludovicus: I'll keep checking to see whether I can replicate the circumstances for the original output.

**Comment by Aldavor** [comment]
I'll close this since I haven't been able to replicate the exact circumstances or the issue as initially described. I'll open another issue if I come across it again.
