### ISSUE TITLE
Spires of Arak error (swatter)

### ISSUE THREAD

**Issue by Aldavor** [Jiyambi/WoW-Pro-Guides#396]
The following window appeared after handing in the quest "One of our Own" (35274 Alliance) and as the next step appeared ("Inspecting the Troops" 35276):

Date: 2015-01-14 18:50:22
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\WoWPro\WoWPro_Broker.lua line 477:
   attempt to index field 'ocompleted' (a nil value)
Debug:
   WoWPro\WoWPro_Broker.lua:477: NextStep()
   WoWPro\WoWPro_Broker.lua:902: NextStepNotSticky()
   WoWPro\WoWPro_Mapping.lua:464: MapPoint()
   WoWPro\WoWPro_Broker.lua:950: CompleteStep()
   WoWPro\WoWPro_Events.lua:164: AutoCompleteQuestUpdate()
   WoWPro\WoWPro_Events.lua:658:
      WoWPro\WoWPro_Events.lua:388
Locals:
k = 65
i = 1
GID = "EmmSoArak"
skip = false
QID = "35276"
qid = 35276
numquesttext = 1
complete = true
(for index) = 1
(for limit) = 1
(for step) = 1
l = 1
lquesttext = "2"
lcomplete = false
(*temporary) = nil
(*temporary) = 2
(*temporary) = "2"
(*temporary) = 2
(*temporary) = 35276
(*temporary) = 35276
(*temporary) = 35276
(*temporary) = 35276
(*temporary) = 35276
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'ocompleted' (a nil value)"
QidMapReduce = <function> defined @Interface\AddOns\WoWPro\WoWPro_Broker.lua:8
Rep2IdAndClass = <table> {
 good friend = <table> {
 }
 best friend = <table> {
 }
 hated = <table> {
 }
 friend = <table> {
 }
 friendly = <table> {
 }
 stranger = <table> {
 }
 revered = <table> {
 }
 honored = <table> {
 }
 hostile = <table> {
 }
 buddy = <table> {
 }
 unfriendly = <table> {
 }
 neutral = <table> {
 }
 exalted = <table> {
 }
 acquaintance = <table> {
 }
}

AddOns:
  BlizzBugsSuck, v6.0.3.2
  Swatter, v5.21c.5521 (SanctimoniousSwamprat)
  Accountant, v6.01.60000
  Ace3, v
  ACP, v3.4.14 
  Arh, v1.4.2
  AskMrRobot, v19
  AucAdvanced, v5.21c.5521 (SanctimoniousSwamprat)
  AucFilterBasic, v5.21c.5521 (SanctimoniousSwamprat)
  AucFilterOutlier, v5.21c.5521.5459(5.21c/embedded)
  AucMatchUndercut, v5.21c.5521.5507(5.21c/embedded)
  AucScanData, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatHistogram, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatiLevel, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatPurchased, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatSales, v5.21c.5521.5476(5.21c/embedded)
  AucStatSimple, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatStdDev, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatWOWEcon, v5.21c.5521.5323(5.21c/embedded)
  AucUtilAHWindowControl, v5.21c.5521.5347(5.21c/embedded)
  AucUtilAppraiser, v5.21c.5521.5495(5.21c/embedded)
  AucUtilAskPrice, v5.21c.5521.5447(5.21c/embedded)
  AucUtilAutoMagic, v5.21c.5521.5443(5.21c/embedded)
  AucUtilCompactUI, v5.21c.5521.5496(5.21c/embedded)
  AucUtilEasyBuyout, v5.21c.5521.5507(5.21c/embedded)
  AucUtilFixAH, v5.21c.5521 (SanctimoniousSwamprat)
  AucUtilItemSuggest, v5.21c.5521.5417(5.21c/embedded)
  AucUtilPriceLevel, v5.21c.5521.5458(5.21c/embedded)
  AucUtilScanButton, v5.21c.5521.5403(5.21c/embedded)
  AucUtilScanFinish, v5.21c.5521.5515(5.21c/embedded)
  AucUtilScanProgress, v5.21c.5521.4979(5.21c/embedded)
  AucUtilScanStart, v5.21c.5521.5347(5.21c/embedded)
  AucUtilSearchUI, v5.21c.5521.5515(5.21c/embedded)
  AucUtilSimpleAuction, v5.21c.5521.5514(5.21c/embedded)
  AucUtilVendMarkup, v5.21c.5521.4828(5.21c/embedded)
  Babylonian, v5.1.DEV.332(/embedded)
  BadBoy, v12.504
  BagBrother, v6.0.16
  Bagnon, v6.0.16
  Bazooka, vv2.4.2
  BeanCounter, v5.21c.5521 (SanctimoniousSwamprat)
  Breeze, vv1.10
  ButtonForge, v0.9.38
  Carbonite, v6.0.1
  CarboniteInfo, v1.0
  CarboniteNotes, v1.1
  CarboniteNotesSample, v1.0
  CarboniteQuests, v1.0
  CarboniteSocial, v1.0
  CarboniteWarehouse, v1.0
  CarboniteWeekly, v1.0
  Configator, v5.1.DEV.376(/embedded)
  DebugLib, v5.1.DEV.337(/embedded)
  GatherMate2, v1.33.4
  Grail, v067
  HealBot, v6.0.3.9
  HealBotTips, v6.0.3.9
  Informant, v5.21c.5521 (SanctimoniousSwamprat)
  LibExtraTip, v5.12.DEV.363(/embedded)
  MasterPlan, v0.23.1
  MineOMatic, v6.0.3.007
  MogIt, v3.4.0
  MyBits, v
  NugComboBar, v
  omouse, v0.1.4
  Pawn, v1.9.12
  Postal, v3.5.1
  Skada, v1.4-27
  Stubby, v5.21c.5521 (SanctimoniousSwamprat)
  TheUndermineJournal, v3.3.20150113
  TipHelper, v5.12.DEV.351(/embedded)
  TomTom, vv60000-1.1.1
  WIM, v3.6.23
  WoWPro, v6.0.3J
  WoWProAchievements, v6.0.3J
  WoWProDailies, v6.0.3J
  WoWProLeveling, v6.0.3J
  WowProProfession, v6.0.3J
  WoWProRecorder, v6.0.0
  WoWProWorldEvents, v6.0.3J
  BlizRuntimeLib_enUS v6.0.3.60000 <none>
  (ck=b18)

**Comment by Ludovicus** [comment]
Good catch and a perfect stack trace.

fixed in https://github.com/Jiyambi/WoW-Pro-Guides/commit/f328ae4fb2bf448264d261f4f8fdeac22f39dd40
