### ISSUE TITLE
Shadowmoon Valley (at step 420)

### ISSUE THREAD

**Issue by Aldavor** [Jiyambi/WoW-Pro-Guides#399]
Following popup after collecting/looting item "Bouquet of Dried Flowers" (item 113547):

Date: 2015-01-17 09:25:41
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\WoWPro\WoWPro.lua line 63:
   bad argument #4 to 'format' (string expected, got nil)
Debug:
   [C]: format()
   WoWPro\WoWPro.lua:63: print()
   WoWPro\WoWPro_Broker.lua:911: NextStepNotSticky()
   WoWPro\WoWPro_Mapping.lua:464: MapPoint()
   WoWPro\WoWPro_Broker.lua:333:
      WoWPro\WoWPro_Broker.lua:214
   (tail call): ?
   [C]: ?
   [string "safecall Dispatcher[1]"]:9:
      [string "safecall Dispatcher[1]"]:5
   (tail call): ?
   ...nterface\AddOns\Ace3\AceBucket-3.0\AceBucket-3.0.lua:118: func()
   Ace3\AceTimer-3.0\AceTimer-3.0.lua:55:
      Ace3\AceTimer-3.0\AceTimer-3.0.lua:48
Locals:
None
AddOns:
  BlizzBugsSuck, v6.0.3.2
  Swatter, v5.21c.5521 (SanctimoniousSwamprat)
  Accountant, v6.01.60000
  Ace3, v
  ACP, v3.4.14 
  Arh, v1.4.2
  AskMrRobot, v19
  AucAdvanced, v5.21c.5521 (SanctimoniousSwamprat)
  AucFilterBasic, v5.21c.5521 (SanctimoniousSwamprat)
  AucFilterOutlier, v5.21c.5521.5459(5.21c/embedded)
  AucMatchUndercut, v5.21c.5521.5507(5.21c/embedded)
  AucScanData, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatHistogram, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatiLevel, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatPurchased, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatSales, v5.21c.5521.5476(5.21c/embedded)
  AucStatSimple, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatStdDev, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatWOWEcon, v5.21c.5521.5323(5.21c/embedded)
  AucUtilAHWindowControl, v5.21c.5521.5347(5.21c/embedded)
  AucUtilAppraiser, v5.21c.5521.5495(5.21c/embedded)
  AucUtilAskPrice, v5.21c.5521.5447(5.21c/embedded)
  AucUtilAutoMagic, v5.21c.5521.5443(5.21c/embedded)
  AucUtilCompactUI, v5.21c.5521.5496(5.21c/embedded)
  AucUtilEasyBuyout, v5.21c.5521.5507(5.21c/embedded)
  AucUtilFixAH, v5.21c.5521 (SanctimoniousSwamprat)
  AucUtilItemSuggest, v5.21c.5521.5417(5.21c/embedded)
  AucUtilPriceLevel, v5.21c.5521.5458(5.21c/embedded)
  AucUtilScanButton, v5.21c.5521.5403(5.21c/embedded)
  AucUtilScanFinish, v5.21c.5521.5515(5.21c/embedded)
  AucUtilScanProgress, v5.21c.5521.4979(5.21c/embedded)
  AucUtilScanStart, v5.21c.5521.5347(5.21c/embedded)
  AucUtilSearchUI, v5.21c.5521.5515(5.21c/embedded)
  AucUtilSimpleAuction, v5.21c.5521.5514(5.21c/embedded)
  AucUtilVendMarkup, v5.21c.5521.4828(5.21c/embedded)
  Babylonian, v5.1.DEV.332(/embedded)
  BadBoy, v12.504
  BagBrother, v6.0.16
  Bagnon, v6.0.16
  BagnonConfig, v6.0.16
  Bazooka, vv2.4.2
  BeanCounter, v5.21c.5521 (SanctimoniousSwamprat)
  Breeze, vv1.10
  ButtonForge, v0.9.38
  Carbonite, v6.0.1
  CarboniteInfo, v1.0
  CarboniteNotes, v1.1
  CarboniteNotesSample, v1.0
  CarboniteQuests, v1.0
  CarboniteSocial, v1.0
  CarboniteWarehouse, v1.0
  CarboniteWeekly, v1.0
  Configator, v5.1.DEV.376(/embedded)
  DebugLib, v5.1.DEV.337(/embedded)
  Enchantrix, v5.21c.5521 (SanctimoniousSwamprat)
  EnchantrixBarker, v5.21c.5521 (SanctimoniousSwamprat)
  GatherMate2, v1.33.4
  Grail, v067
  HealBot, v6.0.3.9
  HealBotTips, v6.0.3.9
  Informant, v5.21c.5521 (SanctimoniousSwamprat)
  LibExtraTip, v5.12.DEV.363(/embedded)
  MasterPlan, v0.24.1
  MineOMatic, v6.0.3.007
  MogIt, v3.4.0
  MyBits, v
  NugComboBar, v
  NugComboBarGUI, v
  omouse, v0.1.4
  Pawn, v1.9.12
  Postal, v3.5.1
  Skada, v1.4-28
  Stubby, v5.21c.5521 (SanctimoniousSwamprat)
  TheUndermineJournal, v3.3.20150117
  TipHelper, v5.12.DEV.351(/embedded)
  TomTom, vv60000-1.1.1
  WIM, v3.6.23
  WoWPro, v6.0.3J
  WoWProAchievements, v6.0.3J
  WoWProDailies, v6.0.3J
  WoWProLeveling, v6.0.3J
  WowProProfession, v6.0.3J
  WoWProRecorder, v6.0.0
  WoWProWorldEvents, v6.0.3J
  BlizRuntimeLib_enUS v6.0.3.60000 <none>
  (ck=bae)

**Comment by Ludovicus** [comment]
Fixed for 6.1.1A, which will be out in a few days.
