### ISSUE TITLE
Treasure: Mushroom-Covered Chest Umbrafen

### ISSUE THREAD

**Issue by Aldavor** [Jiyambi/WoW-Pro-Guides#403]
Incorrect QID; the line (615) in Shadowmoon levelling guide should be changed from:

> l Mushroom-Covered Chest |QID|33869|N|Mushroom-Covered Chest: Lootable object found at the bottom of the lake in Umbrafen.|M|52.87,24.85|RANK|3|

to:

> l Mushroom-Covered Chest |QID|37254|N|Mushroom-Covered Chest: Lootable object found at the bottom of the lake in Umbrafen.|M|52.87,24.85|RANK|3|

**Comment by Ludovicus** [comment]
Excellent catch.  The old QID was for "Treasure: Elekk Horn".
Corrected on the website.  Out in the next update.
