### ISSUE TITLE
Request: Draenor quests dependencies

### ISSUE THREAD

**Issue by Aldavor** [Jiyambi/WoW-Pro-Guides#404]
From looking at the Wiki here, I'm not sure if anything exists to check for specific Outpost buildings having been selected. Many quests depend on the type of building chosen to build in Gorgrond, Talador and Nagrand. For instance, if the Sparring Arena is selected for Highpass, Gorgrond, then quests such as "Beatface vs Boulder" (36438) are available.

Would it be possible to include such a thing to allow for quest guide tagging?

**Comment by Emmaleah** [comment]
How I did it was using the PRE tag. In the Horde guides you shouldn't be
offered any quests by the guide that the game does not offer.  The only
exception to this would be all the rocks and vines in gorgrond since once
they are opened (by someone with the appropriate building type) they can be
looted by anyone for a couple of minutes.

**Comment by Aldavor** [comment]
Yes; I was thinking of that, but given the example above (which is the Alliance one), it would rely on at least the first quest after building the arena having been completed by the user ("A Rediscovered Legend" - 34704) which would be appended to the PRE tag (PRE|36436;34704|). Another way is by using the spell ID of "Champion's Honor" (164221) in some way, as being in the user inventory. At the moment, the guide only offers "Shredder vs Saberon" (36439) which is only available if the Lumber Mill is selected.

Just spitballing here btw... ;)

**Comment by Ludovicus** [comment]
I did not bother looking through the API for garrisons to detect outpost buildings.
I think selection using the PRE tag suffices for now.

Though I personally, after the leveling crush is over, now find that I never find a vine in gorgrond open when I can only do rocks.

**Comment by Emmaleah** [comment]
I will look over the alliance one, it took me a bit of thinking to get it
right for horde.

As to the vines vs. boulders
I on purpose left it so both show. (When on rank 3) .  My logic was that
anyone who cares enough to be on rank 3, probably is willing to either have
a friend who can open the opposite type or they can handle manually
checking off the ones that don't get open by random strangers.

**Comment by Aldavor** [comment]
I've replaced the relevant section with this for now:
>A Shredder vs. Saberon |QID|36439|N|From Altauur|M|51.31,47.97|PRE|36436,35708|
R Steamscar Rise|QID|36439|N|Head to Steamscar Rise|M|52.29,46.52|ACTIVE|36439|
C Shredder vs. Saberon |QID|36439|N|Head up the path, break the Strong Vine Barricade, then walk in.|NC|M|52.22,48.66|
T Shredder vs. Saberon |QID|36439|N|To Altauur, who is moving into Steamscar Rise after you broke in.|M|52.04,49.50|PRE|36436,35708|
; [aldavor] Added beatface vs boulder track for sparring ring CHECK THESE - 1st not appearing
A Beatface vs. Boulder |QID|36438|N|From Altauur|M|51.31,47.97|PRE|36436,34704|
C Beatface vs. Boulder |QID|36438|N|Leave the cave and go left; there is a trail with a red banner over it heading up the mountain that brings you into a spot full of dead podlings|NC|M|50.61,51.44|ACTIVE|36438|
T Beatface vs. Boulder |QID|36438|N|To Altauur, who will spawn to your right as soon as you walk into the encampment.|M|52.04,49.50|PRE|36436,34704|
; [aldavor] CHECK PRE FOR THIS ONE - 1st one not appearing
A Saberon Population Reduction |QID|36440|N|From Altauur|M|52.04,49.50|PRE|36439|

but as you can see, I'm having issues with two of the entries not appearing as they should; however, you're right in that the PRE additions do seem to make it work.

**Comment by Ludovicus** [comment]
Oh.  Thats easy.  |PRE|36436;34704|.  The separator for multiple PRE quests is a semicolon, not a comma.

**Comment by Aldavor** [comment]
I'll add this to the website source - as far as I can tell it works now.

**Comment by Aldavor** [comment]
Closing this as it's been committed.
