### ISSUE TITLE
Alliance - 90_92_Fluclo_Shadowmoon.lua Change

### ISSUE THREAD

**Issue by Aldavor** [Jiyambi/WoW-Pro-Guides#406]
In this guide relative to "Pipper's Buried Supplies", line 250 states that it never completes; that's because there's not just one supply bag to be found. There are four, and each one can be found by following Shelly's dog Pippers. Once all four are picked up, the quest completes.

I would suggest the following change to line 251 from:
>l Pippers' Buried Supplies|QID|35384|N|Pippers' Burried Supplies: Lootable object for Garrison Resources. Can be at one of four locations around the garrison.|CS|M|46.3,75.9;60.7,55.3;51.7,44.9;30.8,28.3|RANK|3|Z|Lunarfall|LEAD|35381;35382;35383|

to:
>l Pippers' Buried Supplies|QID|35384|N|Garrison Resources found at four different locations around the garrison. Follow Pippers the dog until it stops, and click on the sack-thing (if you already have it, there will just be bones).|CS|M|46.3,75.9;60.7,55.3;51.7,44.9;30.8,28.3|RANK|3|Z|Lunarfall|LEAD|35381;35382;35383|

**Comment by Ludovicus** [comment]
Excellent!  I'll add that and a |T|Pippers|  

I think the locations of the items also shifts depending on the level of your garrison.

**Comment by Aldavor** [comment]
Yes they do... perhaps remove the waypoints as, since the dog will be followed, they'll be irrelevant.

**Comment by Ludovicus** [comment]
Done.
