### ISSUE TITLE
WowPro:RegisterGuide error

### ISSUE THREAD

**Issue by Aldavor** [Jiyambi/WoW-Pro-Guides#407]
I still keep getting this appear on character login, in the chat window during initialisation:
>WoWPro: WoWPro:RegisterGuide(TwiSkyRace,Dailies,...) has bad gtype

**Comment by Ludovicus** [comment]
Ah.  There was a duplicate guide on the disk!
Deleted ./WoWPro_Achievements/General/Twists_SkyRace.lua
