### ISSUE TITLE
Suggested additions to 95_96_Ludovico_Talador.lua

### ISSUE THREAD

**Issue by Aldavor** [Jiyambi/WoW-Pro-Guides#408]
File: WoWPro_Levelling/Alliance/95_96_Ludovico_Talador.lua

After this current line 191:
>T New Owner|QID|35239|M|62.89,50.46|N|To Pleasure-Bot 8000|

Add:
>; [aldavor] replace this line with a quest not included in this guide yet...
A A Pilgrimage Gone Awry|QID|34802|M|61.4,54.3|N|Pick up this quest from Nadur|
C A Pilgrimage Gone Awry|QID|34802|S|N|Kill Ridge Prowlers (and cubs) for Prowler Blood, Snapdragon Fronds are growing plants, loot Riverhopper Eye from frogs/toads|
T A Pilgrimage Gone Awry|QID|34802|M|61.4,54.3|N|To Nadur|
; [aldavor]Put the Ra'Khan boss into here with replacement text (original line was at the end of the guide)
K Ra'kahn|M|59.48,59.59|RANK|3|QID|34196|N|Rare kill; may drop Ra'kahn's Bite (i563 Fist Weapon). Head SW from Nadur, cave entrance is 60.1,57.5.|
; [aldavor] Get back to the road to get Hilaani.
R Tomb of Lights|QID|34578|M|63.45,61.83|CS|N|Next, near the Tomb of Lights.|

and remove existing line 193:
>  R Tomb of Lights|QID|34578|M|61.87,52.16;61.00,53.62;62.43,56.83;63.45,61.83|CS|N|Next, Near Tomb of Lights!|

to continue with:
> C Wanted: Hilaani|QID|34104|M|66.21,65.30|N|Hilaani, between Tombs of Light and Gordal Fortress, waaay to the south of fort. Party of 3 suggested.|

Please note that the new lines will probably need "tidying" as I'm not sure the syntax is correct.

**Comment by Ludovicus** [comment]
Edit made.
