### ISSUE TITLE
wow-pro.com cannot send email

### ISSUE THREAD

**Issue by luisb** [Jiyambi/WoW-Pro-Guides#409]
Apologies for creating an issue about the website here. I didn't notice an obvious alternative. I've tried contacting the email address given by the site to no avail. I'm trying to register on wow-pro.com, however the site is unable to email me credentials, the link to confirm registration or whatever I need to complete registration. "Forgot my password" fails to send emails as well. I've attached a screenshot of the error message the site give.

Thanks for your attention.

![screen shot 2015-01-22 at 6 30 50 pm](https://cloud.githubusercontent.com/assets/130465/6132315/998da8d8-b106-11e4-84c3-3b696180d1f8.png)

**Comment by Ludovicus** [comment]
You are probably not sending to the right email address.
This is the address: WoW Pro 2OO4 at Outlook dot com.

Type it by hand and do not cut and paste as there are unicode characters in there and spaces to fool email address scrapers.
