### ISSUE TITLE
Incorrect QID in Alliance\95_96_Ludovico_Talador.lua

### ISSUE THREAD

**Issue by Aldavor** [Jiyambi/WoW-Pro-Guides#411]
WoWPro_Leveling\Alliance\95_96_Ludovico_Talador.lua:

All references to "Wanted: Ra'tok the Hammer" should be QID 34105 (34106 is Horde QID).

**Comment by Ludovicus** [comment]
Is there a reason you can't make the change on the website?
I thought I activated your account.

**Comment by Aldavor** [comment]
Sorry, haven't really got there yet... will do tonight. Is it preferable for all such changes to be made on the site?
