### ISSUE TITLE
Swatter error in Pandaria

### ISSUE THREAD

**Issue by Aldavor** [Jiyambi/WoW-Pro-Guides#414]
Got this while flying to Timeless Isle, and selecting the Emperor Shaohan daily quest from the Guide list.

Date: 2015-02-21 10:53:33
ID: 2
Error occured in: Global
Count: 1
Message: ...e\AddOns\WoWPro_Dailies\WoWPro_Dailies_GuideList.lua line 116:
   bad argument #1 to 'unpack' (table expected, got no value)
Debug:
   [C]: unpack()
   ...e\AddOns\WoWPro_Dailies\WoWPro_Dailies_GuideList.lua:116: GuideTooltipInfo()
   WoWPro\WoWPro_GuideList.lua:204:
      WoWPro\WoWPro_GuideList.lua:203
Locals:
(*temporary) = "table expected, got no value"

AddOns:
  BlizzBugsSuck, v6.0.3.2
  Swatter, v5.21c.5521 (SanctimoniousSwamprat)
  Accountant, v6.01.60000
  Ace3, v
  ACP, v3.4.14 
  Arh, v1.4.2
  AskMrRobot, v19
  AucAdvanced, v5.21c.5521 (SanctimoniousSwamprat)
  AucFilterBasic, v5.21c.5521 (SanctimoniousSwamprat)
  AucFilterOutlier, v5.21c.5521.5459(5.21c/embedded)
  AucMatchUndercut, v5.21c.5521.5507(5.21c/embedded)
  AucScanData, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatHistogram, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatiLevel, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatPurchased, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatSales, v5.21c.5521.5476(5.21c/embedded)
  AucStatSimple, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatStdDev, v5.21c.5521 (SanctimoniousSwamprat)
  AucStatWOWEcon, v5.21c.5521.5323(5.21c/embedded)
  AucUtilAHWindowControl, v5.21c.5521.5347(5.21c/embedded)
  AucUtilAppraiser, v5.21c.5521.5495(5.21c/embedded)
  AucUtilAskPrice, v5.21c.5521.5447(5.21c/embedded)
  AucUtilAutoMagic, v5.21c.5521.5443(5.21c/embedded)
  AucUtilCompactUI, v5.21c.5521.5496(5.21c/embedded)
  AucUtilEasyBuyout, v5.21c.5521.5507(5.21c/embedded)
  AucUtilFixAH, v5.21c.5521 (SanctimoniousSwamprat)
  AucUtilItemSuggest, v5.21c.5521.5417(5.21c/embedded)
  AucUtilPriceLevel, v5.21c.5521.5458(5.21c/embedded)
  AucUtilScanButton, v5.21c.5521.5403(5.21c/embedded)
  AucUtilScanFinish, v5.21c.5521.5515(5.21c/embedded)
  AucUtilScanProgress, v5.21c.5521.4979(5.21c/embedded)
  AucUtilScanStart, v5.21c.5521.5347(5.21c/embedded)
  AucUtilSearchUI, v5.21c.5521.5515(5.21c/embedded)
  AucUtilSimpleAuction, v5.21c.5521.5514(5.21c/embedded)
  AucUtilVendMarkup, v5.21c.5521.4828(5.21c/embedded)
  Babylonian, v5.1.DEV.332(/embedded)
  BadBoy, v12.511
  BagBrother, v6.0.16
  Bagnon, v6.0.16
  BagnonConfig, v6.0.16
  Bazooka, vv2.4.3
  BeanCounter, v5.21c.5521 (SanctimoniousSwamprat)
  Breeze, vv1.31
  ButtonForge, v0.9.38
  Carbonite, v6.0.1
  CarboniteInfo, v6.0
  CarboniteNotes, v6.0.1
  CarboniteNotesSample, v1.0
  CarboniteQuests, v6.0.1
  CarboniteSocial, v6.0.1
  CarboniteWarehouse, v6.0.1
  CarboniteWeekly, v6.0.1
  Configator, v5.1.DEV.376(/embedded)
  DebugLib, v5.1.DEV.337(/embedded)
  Enchantrix, v5.21c.5521 (SanctimoniousSwamprat)
  EnchantrixBarker, v5.21c.5521 (SanctimoniousSwamprat)
  GatherMate2, v1.33.4
  Grail, v067
  HealBot, v6.0.3.10
  HealBotTips, v6.0.3.10
  Informant, v5.21c.5521 (SanctimoniousSwamprat)
  LibExtraTip, v5.12.DEV.363(/embedded)
  MasterPlan, v0.28
  MineOMatic, v6.0.3.008
  MogIt, v3.4.0
  MyBits, v
  NugComboBar, v
  NugComboBarGUI, v
  omouse, v0.1.4
  Pawn, v1.9.13
  Postal, v3.5.1
  Prat30, v3.5.11      
  Prat30Libraries, v
  QuestCompletist, v101
  Skada, v1.4-28
  Stubby, v5.21c.5521 (SanctimoniousSwamprat)
  TheUndermineJournal, v3.4.20150221
  TipHelper, v5.12.DEV.351(/embedded)
  TomTom, vv60000-1.1.1
  WIM, v3.6.24
  WoWPro, v6.0.4
  WoWProAchievements, v6.0.4
  WoWProDailies, v6.0.4
  WoWProLeveling, v6.0.4
  WoWProProfession, v6.0.4
  WoWProWorldEvents, v6.0.4
  BlizRuntimeLib_enUS v6.0.3.60000 <none>
  (ck=bde)

**Comment by Ludovicus** [comment]
Fix queued up for 6.1.1A
