### ISSUE TITLE
Azuremist Isle starter zone errors

### ISSUE THREAD

**Issue by Aldavor** [Jiyambi/WoW-Pro-Guides#416]
I'm getting a load of "xxx has an unknown tag |R|" and unknown tag "|C|" right on rolling a new Draenei, in the WowPro chat window output. I've looked at replacing these to "|RACE|" but makes no difference, still doesn't recognise that too. Any suggestions?

**Comment by Ludovicus** [comment]
LOL,  you pulled a copy of the repository before https://github.com/Jiyambi/WoW-Pro-Guides/commit/5e52d2493e37b494a49c0ab9e2da7aad87d0739a (Improve empty tag handling. Add R/C/GEN tags).   Update to the latest.  I'm tagging it right now as 6.1.1 .
