### ISSUE TITLE
Outland - shadowmoon valley

### ISSUE THREAD

**Issue by Aldavor** [Jiyambi/WoW-Pro-Guides#417]
There seems to be an issue with 70_70_Crackerhead22_Shadowmoon.lua (Alliance) in that, although the map coordinates are correct, the arrow points somewhere completely different, which leads me to believe TomTom is at fault. Is there any notes as to whether the Zone name (|Z|) should be different or changed in the guide files to allow for this?

**Comment by Ludovicus** [comment]
Which step are you near where you saw this problem?  
What version of the addon are you using?
What version of TomTom are you using?

The guide itself uses the default zone of "Shadowmoon Valley" which is correct, and WoWPro maps that to map 473 which should be right.  I flew out there on my L71 Belf BDK and she saw no mapping problems.

Need more information!

**Comment by Ludovicus** [comment]
Any updates, @Aldavor ?

**Comment by Aldavor** [comment]
Sorry not had a chance to go through that area with any of my toons. I'll check during this week; sorry for the delay.

**Comment by Ludovicus** [comment]
No problem, just wanted to follow up.  If you can get me info over the next few days I can address it more quickly, as I have Friday off.

**Comment by Ludovicus** [comment]
OK.  I found the problem when trying to set map entries for my new music box guide.
There was an override entry for Shadowmoon valley that threw them up to Netherstorm.
 Fixed in fe5e452f48612a8d0d3d242b59283b355a25b9eb
