### ISSUE TITLE
Lua Errors using Carbonite for Mapping

### ISSUE THREAD

**Issue by luisb** [Jiyambi/WoW-Pro-Guides#418]
Immediately upon login two LUA errors fire off and interrupt WoW-Pro functionality. It doesn't matter which character or zone, so it seems to be more of an issue with interfacing with Carbonite. Here are the two errors, separated by a line of dashes:

Message: Interface\AddOns\Carbonite\NxMap.lua:9361: attempt to index field 'Quest' (a nil value)
Time: Mon Mar 23 15:15:21 2015
Count: 1
Stack: Interface\AddOns\Carbonite\NxMap.lua:9543: in function <Interface\AddOns\Carbonite\NxMap.lua:9538>
(tail call): ?
Interface\AddOns\WoWPro\WoWPro_Mapping.lua:609: in function `MapPoint'
Interface\AddOns\WoWPro\WoWPro_Events.lua:210: in function `AutoCompleteQuestUpdate'
Interface\AddOns\WoWPro\WoWPro_Parser.lua:611: in function <Interface\AddOns\WoWPro\WoWPro_Parser.lua:540>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...nterface\AddOns\Ace3\AceBucket-3.0\AceBucket-3.0.lua:118: in function `func'
Interface\AddOns\Ace3\AceTimer-3.0\AceTimer-3.0.lua:55: in function <Interface\AddOns\Ace3\AceTimer-3.0\AceTimer-3.0.lua:48>

Locals: <none>

---------

Message: Interface\AddOns\Carbonite\NxMap.lua:9361: attempt to index field 'Quest' (a nil value)
Time: Mon Mar 23 15:15:24 2015
Count: 1
Stack: Interface\AddOns\Carbonite\NxMap.lua:9543: in function <Interface\AddOns\Carbonite\NxMap.lua:9538>
(tail call): ?
Interface\AddOns\WoWPro\WoWPro_Mapping.lua:609: in function `MapPoint'
Interface\AddOns\WoWPro\WoWPro_Events.lua:210: in function `AutoCompleteQuestUpdate'
Interface\AddOns\WoWPro\WoWPro_Events.lua:669: in function <Interface\AddOns\WoWPro\WoWPro_Events.lua:397>

Locals: self = <table> {
 GetDataToolBar = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:1677
 modules = <table> {
 }
 CancelTimer = <function> defined @Interface\AddOns\Ace3\AceTimer-3.0\AceTimer-3.0.lua:145
 OnUnit_spellcast_sent = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:1052
 prt = <function> defined @Interface\AddOns\Carbonite\NxUI.lua:95
 BarData = <table> {
 }
 prtVar = <function> defined @Interface\AddOns\Carbonite\NxUI.lua:159
 ScheduleTimer = <function> defined @Interface\AddOns\Ace3\AceTimer-3.0\AceTimer-3.0.lua:92
 GroupMembers = <table> {
 }
 ADDON_LOADED = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:770
 prtFrame = <function> defined @Interface\AddOns\Carbonite\NxUI.lua:196
 db = <table> {
 }
 UnregisterAllComm = <function> defined @Interface\AddOns\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:202
 SetEnabledState = <function> defined @Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:455
 Graph = <table> {
 }
 ShowEditBox = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:1326
 GatherInit = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:3117
 prtTable = <function> defined @Interface\AddOns\Carbonite\NxUI.lua:144
 Font = <table> {
 }
 Util_TMoveI = <function> defined @Interface\AddOns\Carbonite\NxUI.lua:341
 Combat = <table> {
 }
 NewModule = <function> defined @Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:266
 MenuI = <table> {
 }
 VERSIONList = 0.1
 ClearSocial = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:2692
 OnPlayer_regen_enabled = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:1048
 ModuleUpdateIcon = <table> {
 }
 Initialized = true
 Script = <table> {
 }
 UNIT_NAME_UPDATE = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:774
 VERSIONCAP = 0.75
 GetName = <function> defined @Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:310
 GatherMine = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:3186
 MapOverlayToMapId = <table> {
 }
 Disable = <function> defined @Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:345
 GatherUnpack = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:3241
 VERSIONHUDOPTS = 0.03
 GatherDeleteHerb = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:3250
 TabBar = <table> {
 }
 Window = <table> {
 }
 Print = <function> defined @Interface\AddOns\Ace3\AceConsole-3.0\AceConsole-3.0.lua:54
 Util_SnapToScreen = <function> defined @Interface\AddOns\Carbonite\NxUI.lua:552
 NPCData = <table> {
 }
 Tick = 78
 UnitDTip = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:967
 UnpackEvent = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:2021
 ToolBar = <table> {
 }
 FindCharacter = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:1837
 RegisterComm = <function> defined @Interface\AddOns\Ace3\AceComm-3.0\AceComm-3.0.lua:61
 MapWorldHotspots = <table> {
 }
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:398
 ModQAction = ""
 AddEvent = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:1976
 EnableModule = <function> defined @Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:363
 IterateEmbeds = <function> defined @Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:473
 GetEventMapId = <function> defined @Interface\AddOns\Carbonite\Carbonite.lua:2012
 Util_SecondsToDays = <function> defined @Interface\AddOn

**Comment by Ludovicus** [comment]
What version of WoWPro and Carbonite are you using?

**Comment by Ludovicus** [comment]
I suspect it is a Carbonite issue:

```
--------
-- Set map target at zone xy (pos 0-100)
-- Ret target table

function Nx.Map:SetTargetXY (mid, zx, zy, name, keep)
if Nx.Quest.Watch then
	Nx.Quest.Watch:ClearAutoTarget()
end
	local wx, wy = self:GetWorldPos (mid, zx, zy)
	return self:SetTarget ("Goto", wx, wy, wx, wy, nil, nil, name or "", keep, mid)
end

--------
-- Set map target at mouse click

function Nx.Map:SetTargetAtClick()
if Nx.Quest and Nx.Quest.Watch then
	Nx.Quest.Watch:ClearAutoTarget()
end
	local wx, wy = self:FramePosToWorldPos (self.ClickFrmX, self.ClickFrmY)
	local zx, zy = self:GetZonePos (self.MapId, wx, wy)
	local str = format ("Goto %.0f, %.0f", zx, zy)

	self:SetTarget ("Goto", wx, wy, wx, wy, nil, nil, str, IsShiftKeyDown())
end
```

Note how access to Nx.Quest.Watch is protected in the second function, but not the first.

**Comment by luisb** [comment]
Apologies I meant to include that in my report. I'm using the latest pull (as of the time of the report) from GitHub. 

-Luis

**Comment by Ludovicus** [comment]
BTW, I also suspect that if you load the Carbonite quest module, that the error will also go away.
Anyways.  This is a Carbonite issue and not a WoWPro issue.   You should file a report with them.
