### ISSUE TITLE
Lua Error rendering guide unusable.

### ISSUE THREAD

**Issue by Sumgi** [Jiyambi/WoW-Pro-Guides#422]
First appeared mid way through Hellfire Peninsula, after a small break with addon disabled as I played around in early durotar to grind out a little Org rep. Upon reenabling, anytime the addon loads up or I switch guides, or do part of a quest, or kill a creature needed for part of a quest. I get a lua error shown below. This occurs even after switching from 6.1.1.A to the current testing version, or completely deleting and reinstalling the addon, including delete the saved variables from the WTF folder. ALso the text keeps getting truncated in odd places.

LUA error

Message: Interface\AddOns\WoWPro\WoWPro_Events.lua:351: attempt to index field 'leaderBoard' (a nil value)
Time: 04/24/15 01:45:45
Count: 1
Stack: (tail call): ?
(tail call): ?
Interface\AddOns\WoWPro\WoWPro_Events.lua:351: in function `UpdateQuestTracker'
Interface\AddOns\WoWPro\WoWPro_Parser.lua:919: in function `RowUpdate'
Interface\AddOns\WoWPro\WoWPro_Broker.lua:265: in function `rowContentUpdate'
Interface\AddOns\WoWPro\WoWPro_Broker.lua:297: in function <Interface\AddOns\WoWPro\WoWPro_Broker.lua:220>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...ce\AddOns\Archy\Libs\AceBucket-3.0\AceBucket-3.0.lua:118: in function `func'
...face\AddOns\Archy\Libs\AceTimer-3.0\AceTimer-3.0.lua:55: in function <...face\AddOns\Archy\Libs\AceTimer-3.0\AceTimer-3.0.lua:48>

Locals: <none>

**Comment by Ludovicus** [comment]
Thats odd.   I thought I fixed that bug before.  I'll look at it after work today.

**Comment by Ludovicus** [comment]
Fixed in 142588841a1ce27fd8cff41d834c35d2590c92d8
