### ISSUE TITLE
K steps do not autocomplete

### ISSUE THREAD

**Issue by taralx** [Jiyambi/WoW-Pro-Guides#423]
K steps (and some others maybe) don't autocomplete. Example log for Iceshatter in Dragonblight (WotLK) follows.

**Comment by taralx** [comment]
https://gist.github.com/taralx/e5c21e07b93381c8e7ed

**Comment by Ludovicus** [comment]
K steps do not autocomplete by design.  The QO tag is supposed to complete them.
I'll have to see what's going on as it works for other guides.
I used it myself last night.

**Comment by Aldavor** [comment]
The QO may need a numeric complete (as in QO|1|) as I've found with other guides.

**Comment by Emmaleah** [comment]
Yes blizzard changed the way it treats them and the text won't work for any
WOD content and sometimes for other content.

**Comment by Ludovicus** [comment]
Sorry for the delay, I had to study your debug log to figure it out, but it is obvious in retrospect.
Here are the critical lines in the log:
```
000554.0032 ~ WoWPro: UI_INFO_MESSAGE("Iceshatter slain: 1/1") InitLockdown=false
000554.0057 ~ WoWPro: profile.track=true action=K questtext=Iceshatter slain: 1/1 lootitem=nil
000554.0058 ~ WoWPro: UQT: QID 12149 active and QO tag of [Iceshatter slain: 1/1]
000554.0059 ~ WoWPro: UQT: Track Text for K [Iceshatter] to ''
000554.0060 ~ WoWPro: profile.track=true action=C questtext=nil lootitem=nil
000554.0061 ~ WoWPro: UQT: QID 12149 active, but no QO tag, lets make something up.
000554.0062 ~ WoWPro: UQT: Track Text for C [Mighty Magnataur] to '- 1/1 Iceshatter slain (C)
- 0/1 Bloodfeast slain
- 1/1 Drakegore slain (C)'
```
Note that even though the UI message says the quest objective is "Iceshatter slain: 1/1", the following catch-all C step says the quest leaderboard is using "1/1 Iceshatter slain".  So no match.
As @Aldavor and @Emmaleah suggested, the QO needs to change to the numeric form.
In this case, the UI and quest are not even consistent!

**Comment by Ludovicus** [comment]
I corrected both Dragonblight guides.

**Comment by taralx** [comment]
Thanks! If I want to fix the rest, do I just submit a PR here?

**Comment by Ludovicus** [comment]
Please don't!    This repository is for the addon.   The guides are managed via a CMS at http://wow-pro.com/node/3594 .   Please register there and make there.

The registration system is having email problems, so after you register, contact the email address indicated to complete the registration process.

**Comment by taralx** [comment]
Sorry to bother you again, but I have an account on the website, but it doesn't let me edit. I sent an email to the contact address on the site, but I don't know if it's any good (jame.wow.pro.blog).

**Comment by Ludovicus** [comment]
The address to send to is WoWPro followed by a date at outlook dot com.
It is on the registration page.
