### ISSUE TITLE
New Starter Human Monk

### ISSUE THREAD

**Issue by Aldavor** [Jiyambi/WoW-Pro-Guides#425]
Just rolled a new human monk, and the guide list doesn't show the Northshire (or Elwynn Forest) guide under the Leveling tab... checked the xml file, and it's in there, but dunno where else to look...?

**Comment by Ludovicus** [comment]
One sec. let me check my list.

**Comment by Ludovicus** [comment]
Edit your Guildes.xml file and correct the following spellings:

```
diff --git a/WoWPro_Leveling/Alliance/Guides.xml b/WoWPro_Leveling/Alliance/Guides.xml
index 7e23aa9..c4d573e 100755
--- a/WoWPro_Leveling/Alliance/Guides.xml
+++ b/WoWPro_Leveling/Alliance/Guides.xml
@@ -1,11 +1,11 @@
 <Ui xmlns="http://www.blizzard.com/wow/ui/">
   <Script file="01_05_Gylin_Dwarf_Starter.lua"/>
   <Script file="01_05_Gylin_Gnome_Starter.lua"/>
-  <Script file="01_05_Kurich_Northshire.lua"/>
-  <Script file="05_11_Kurich_Elwynn.lua"/>  
+  <Script file="01_05_Kurich_Northsire.lua"/>
+  <Script file="05_10_Kurich_Elwynn.lua"/>  
   <Script file="01_05_Bitsem_Shadowglen.lua"/>
   <Script file="05_12_Bitsem_Teldrassil.lua"/>
-  <Script file="01_15_Snowflakes_AmmenVale.lua"/>
+  <Script file="01_05_Snowflakes_AmmenVale.lua"/>
   <Script file="05_12_Snowflakes_Azuremyst.lua"/>
   <Script file="01_13_Rpotor_Worgen_Starter.lua"/>
   <Script file="05_10_Gameldar_Dun_Morogh.lua"/>
```

**Comment by Ludovicus** [comment]
OK.  That should get you started.   I'll correct the Northsire spelling later this morning.  
Review of the FRameXML.log shows that all the named guides are being loaded and spelled correctly.
I'll correct the metadata (guide levels) once you have your work done.

**Comment by Aldavor** [comment]
OK That's worked, although it didn't "auto load" when I loaded my character.

On a similar note, and sorry to ask here (doesn't seem to be a way of sending PMs on here), but what's the URL/node number for the Dwarf starter zone on wow-pro.com? The Dun Morogh only contains the Gnome one and the follow-up levels in DM itself...?

**Comment by Ludovicus** [comment]
The Dun Morogh page has the Gnome (1-5) Dwatf (1-5) and Dun Morogh (5-10) guides one right after the other.  It is all in http://wow-pro.com/node/3200

**Comment by Aldavor** [comment]
I must be blind (or still drunk...); at http://wow-pro.com/node/3200 I can only see the Gnome and Dun Morogh code segments... and also checked on the 'edit' page in case the View was truncating it. Sorry to be a pain...

**Comment by Ludovicus** [comment]
Sorry!!!!!!

I deleted the dwarf starter by accident.   Now restored.

**Comment by Aldavor** [comment]
OK I see it now! :D Thanks :)
