### ISSUE TITLE
Swatter error on create/login to new character

### ISSUE THREAD

**Issue by Aldavor** [Jiyambi/WoW-Pro-Guides#427]
Hi; I rolled a new Nelf rogue, and on login I get this error:

====
Date: 2015-06-25 09:35:33
ID: 1
Error occured in: Global
Count: 1
Message: ...ce\AddOns\WoWPro_Leveling\WoWPro_Leveling_Parser.lua line 58:
   table index is nil
Debug:
   ...ce\AddOns\WoWPro_Leveling\WoWPro_Leveling_Parser.lua:58: NextStep()
   WoWPro\WoWPro_Broker.lua:921: NextStep()
   WoWPro\WoWPro_Parser.lua:703: RowUpdate()
   WoWPro\WoWPro_Broker.lua:282: rowContentUpdate()
   WoWPro\WoWPro_Broker.lua:314:
      WoWPro\WoWPro_Broker.lua:237
   (tail call): ?
   [C]: ?
   [string "safecall Dispatcher[1]"]:9:
      [string "safecall Dispatcher[1]"]:5
   (tail call): ?
   ...nterface\AddOns\Ace3\AceBucket-3.0\AceBucket-3.0.lua:118: func()
   Ace3\AceTimer-3.0\AceTimer-3.0.lua:55:
      Ace3\AceTimer-3.0\AceTimer-3.0.lua:48
Locals:
None
AddOns:
  BlizzBugsSuck, v6.1.0.0
  Swatter, v5.21d2.5561 (SanctimoniousSwamprat)
  Accountant, v6.01.60100
  Ace3, v
  AchievementsReminder, v
  ACP, v3.4.15 
  Arh, v1.4.4
  AskMrRobot, v24
  AucAdvanced, v5.21d2.5561 (SanctimoniousSwamprat)
  AucFilterBasic, v5.21d2.5561 (SanctimoniousSwamprat)
  AucFilterOutlier, v5.21d2.5561.5459(5.21d2/embedded)
  AucMatchUndercut, v5.21d2.5561.5507(5.21d2/embedded)
  AucStatHistogram, v5.21d2.5561 (SanctimoniousSwamprat)
  AucStatiLevel, v5.21d2.5561 (SanctimoniousSwamprat)
  AucStatPurchased, v5.21d2.5561 (SanctimoniousSwamprat)
  AucStatSales, v5.21d2.5561.5476(5.21d2/embedded)
  AucStatSimple, v5.21d2.5561 (SanctimoniousSwamprat)
  AucStatStdDev, v5.21d2.5561 (SanctimoniousSwamprat)
  AucStatWOWEcon, v5.21d2.5561.5323(5.21d2/embedded)
  AucUtilAHWindowControl, v5.21d2.5561.5347(5.21d2/embedded)
  AucUtilAppraiser, v5.21d2.5561.5545(5.21d2/embedded)
  AucUtilAskPrice, v5.21d2.5561.5447(5.21d2/embedded)
  AucUtilAutoMagic, v5.21d2.5561.5537(5.21d2/embedded)
  AucUtilCompactUI, v5.21d2.5561.5550(5.21d2/embedded)
  AucUtilEasyBuyout, v5.21d2.5561.5507(5.21d2/embedded)
  AucUtilFixAH, v5.21d2.5561 (SanctimoniousSwamprat)
  AucUtilItemSuggest, v5.21d2.5561.5417(5.21d2/embedded)
  AucUtilPriceLevel, v5.21d2.5561.5535(5.21d2/embedded)
  AucUtilScanButton, v5.21d2.5561.5403(5.21d2/embedded)
  AucUtilScanFinish, v5.21d2.5561.5515(5.21d2/embedded)
  AucUtilScanProgress, v5.21d2.5561.4979(5.21d2/embedded)
  AucUtilScanStart, v5.21d2.5561.5347(5.21d2/embedded)
  AucUtilSearchUI, v5.21d2.5561.5556(5.21d2/embedded)
  AucUtilSimpleAuction, v5.21d2.5561.5531(5.21d2/embedded)
  AucUtilVendMarkup, v5.21d2.5561.4828(5.21d2/embedded)
  AutoBar, v6.1.0.01
  Babylonian, v5.1.DEV.332(/embedded)
  BadBoy, v12.566
  BagBrother, v
  Bagnon, v6.1.7
  Bazooka, vv2.6.0
  BeanCounter, v5.21d2.5561 (SanctimoniousSwamprat)
  ButtonForge, v0.9.39
  Configator, v5.1.DEV.382(/embedded)
  DebugLib, v5.1.DEV.337(/embedded)
  Enchantrix, v5.21d2.5561 (SanctimoniousSwamprat)
  EnchantrixBarker, v5.21d2.5561 (SanctimoniousSwamprat)
  GatherMate2, v1.33.5
  Grail, v069
  HandyNotes, vv1.3.3
  HandyNotesDraenorTreasures, v1.13
  HealBot, v6.2.0.0
  HealBotTips, v6.2.0.0
  Informant, v5.21d2.5561 (SanctimoniousSwamprat)
  LibExtraTip, v5.12.DEV.384(/embedded)
  MasterPlanA, v
  MogIt, v3.5.1
  MogItAccessories, v
  MyBits, v
  NugComboBar, v
  omouse, v0.1.4
  Panda, v6.0.0.49
  Pawn, v1.9.17
  Postal, v3.5.4
  Prat30, v3.5.15      
  Prat30Libraries, v
  QuestCompletist, v105
  RaidAchieveFilter, v1.8.3
  RaidAchievement, v
  RaidAchievementOldModules, v
  Skada, v1.4-31
  SlideBar, v5.21d2.5561 (SanctimoniousSwamprat)
  Stubby, v5.21d2.5561 (SanctimoniousSwamprat)
  TheUndermineJournal, v3.4.20150623
  TipHelper, v5.12.DEV.380(/embedded)
  TomTom, vv60100-1.0.0
  WIM, v3.6.27
  WoWPro, v6.2.0
  WoWProAchievements, v6.2.0
  WoWProDailies, v6.2.0
  WoWProLeveling, v6.2.0
  WoWProProfession, v6.2.0
  WoWProWorldEvents, v6.2.0
  BlizRuntimeLib_enUS v6.2.0.60200 <none>
  (ck=bc5)
====

**Comment by Ludovicus** [comment]
Sorry about that.   I'm afraid its my fault.   I'll fix this tonight.

**Comment by Ludovicus** [comment]
Fixed in a5dc0dd51e875ac270c700152bbfd107c10a9a3f
