### ISSUE TITLE
Prereq quest for a quest in guide skipped 

### ISSUE THREAD

**Issue by luisb** [Jiyambi/WoW-Pro-Guides#428]
Ver 6.2.0D, Completeness level 1:
Horde, Crossroads quest "Deathgate's Reinforcements" comes up in the guide however "Kolkar's Leaders" and "A Little Diversion" prereq quests are skipped. See confirmed post in WoWHead: http://www.wowhead.com/quest=14073/deathgates-reinforcements by Lindenkron on 2011/02/12 (Patch 4.0.6).

Workaround: Set completeness level to at least 2.

**Comment by Ludovicus** [comment]
Thanks.  Guide updated to:
```
A Deathgate's Reinforcements|QID|14073|PRE|13992;850|LVL|16|RANK|1|M|48.68,59.54|N|From Thork.|
```
