### ISSUE TITLE
"Use Ability" Tag

### ISSUE THREAD

**Issue by TwoToad** [Jiyambi/WoW-Pro-Guides#50]
There are some quests where you are put into a "mount" to complete the quest. Many guides, thankfully, tell you how to work your new "mount". For example:

C The Iron Colossus |QID|13007| |N|Click on the control orb.  Head south to find the Colossus, you can only move when you're underground (ability 1). Spam 2, use 3 whenever it is up. When he starts to Slam the ground, use 1 to go underground and move behind him. Use 1 again to resurface. Repeat as necessary.| |M|27.16,35.95|

This is from the end of the Storm Peaks guide where you "mount" the giant worm (Jormungar). I was thinking a tag for this might display the abilities next to the guide (similar to the |U| tag) stacked horizontally. It could display the ability names, if the mouse was hovered above the buttons, and show the cooldowns...

An example of how the tag MIGHT look could be (note, these are the abilities/spell id's of Soo-holu, a cat you use for an Oracles quest):

|USEABIL|52331;52358;53032;52327;52321|

If I could have found the "dismount" ability, I would have added that in there as well... I was hoping something like this would show buttons the same size produced by the |U| tag and in a horizontal layout next to the step in the guide.

PS I'm full of mission-impossible suggestions, Sarah... =)
PSS I have no idea how to add this as a "feature" or "request" in github...

**Comment by Ludovicus** [comment]
The vehicle UI now uniformly presents things like this.
We should refrain from providing functionality now present in the base client.
The text, now format-able with \n's does a pretty decent job.
