### ISSUE TITLE
|U| tag for more than one item

### ISSUE THREAD

**Issue by TwoToad** [Jiyambi/WoW-Pro-Guides#51]
Sometimes you need to use more than one item. For example, in the Zul'Drak guide:

C Feedin' Da Goolz |QID|12652| |N|Use the bowl near the ghouls. Be careful of the Blightguards, they see through your disguise. You should hotkey the chocker because your diguise will fail at some point.| |U|38701|

You need to have the choker button up, in case your disguise falls. You also need the button for the bowl of food that you are feeding the ghouls.

Could we get something like |U|12345;67890| or the ability to put 2 |U| tags in one step?

(just noticed that there are misspelled words in Scoot's guide... Bad Scoot, very bad! now I have to do spell checks and re-upload guides hehe)

**Comment by Ludovicus** [comment]
non-coding solution has worked well here and in other guides!
