### ISSUE TITLE
Class Module - access from main guide

### ISSUE THREAD

**Issue by BrianAT** [Jiyambi/WoW-Pro-Guides#76]
I don't see how to mark this as a Request, I clicked the Request on the right and it just loaded up the requests...
I was leveling a new Druid today, had to take a break from the quest guide to get my bear form and it occurred to me that this is a good area for a module. The leveling guide would have something at the start to watch when the player hits 10 to prompt to load the Class Module. Once the Class Module came up it would load the appropriate class leveling guide and guide the person through getting their bear form in this case. Once the full quest line was complete it would turn control back over to the original leveling guide.
Sure the leveling guide itself could have the information needed, but what if the player hits level 10 ahead of the guide. They could wait it out, but why not give them the advantage right away? Plus it would be optional, in the guide itself it just comes up as a sticky step once they hit 10 and once they click it it brings up the dialog box asking if they want to load the guide, which gives them the choice to wait or accept...
At the start of the leveling guide you might have something like this:

G Time to train bear form. |QID|6001| |C|Duid| |O| |S| |LVL=10| |N|You can now train in your bear form. Click here to load the guide to gain this.  You will return to this guide when done.| |CM|Duid-Bear-Alliance.lua|

Or something along those lines anyhow. G (could be M for Module) is my new tag for load guide, |CM| tells it to load the Class Module, others would be |DM| for dungeon module and so on.
This is at the start of the guide, along with other class specific guide loaders (or other module loaders) before the rest of the actual leveling guide loads up, sort of like the header section of an HTML page. The |LVL=10| keeps it from showing up until they hit level 10, at which point this step shows up as a sticky. 
If they click the note, then it brings up a dialog box asking if they want to load the guide or continue questing for now, which leaves the sticky up, but perhaps shrinks it down to just the title and closing the note part. If they choose yes, then it loads the guide as mentioned, which then guides them through the class quest. Once they complete the quest chain, it returns control to the leveling guide they were on.

There are a few key advantages to this. Mainly that this makes leveling guide writing easier, as now they don't have to cover every class quest in the leveling guide. Put the proper headers in at the start and then just worry about the primary leveling tasks. (Obviously the Death Knight guide wouldn't bother since that class has it's own area in full from the start.) It also makes sure that the player gets to see the guide at the proper time in the event they are ahead of where it would be at in the leveling guide. 
For something like swimming form, it would note that it is an optional quest line since you buy the ability now, but it gains reputation. 

Another request, if there is more than one guide for a given starting zone, then it asks which guide to load... of course this would be more needed if there was a way to get rid of guides.xml. That or a way to vote which guides should be the one to represent the starter areas once submissions start coming in. The only example we have at the moment is 000_1_12_Taraloms_nightelf_starter (which was included with the old guide) and 000_1_13_Manovan_night_elf_starter (which I converted as I wanted to be in Darkshore rather than Bloodmist after the guide was done (plus I thought the order was a little better). After that second guide, both guides lead to the same guide from there on out. Anyhow, if we are going to use only one, we should vote on it, or have a way to choose from the start The primary issue I see in removing guides.xml and giving people the ability to choose which guide to load would be support issues. We could only support the "official" guides, any issues the add-on has while using a guide loaded from an outside source wouldn't be supported, but it does make the add-on more powerful and flexible, as people start making their own guides and hosting them on their own. This is sort of very low on the list of priorities, and if two guides are included in the official release and it loads the wrong one, they can manually switch now with no problem, an automated way of picking is just extra filler to add once we have lots of other things put together.

**Comment by Ludovicus** [comment]
We are in the process of adding "triggered" guides for Garrisons that could also handle level triggered and location triggers guide switching.   Closing this off as a duplicate!
